// This file is automatically generated. Do not edit it directly.
import type { Database } from './types';

function isNewSupabaseApiKey(value: string): boolean {
  return value.startsWith('sb_publishable_') || value.startsWith('sb_secret_');
}

function createSupabaseFetch(supabaseKey: string): typeof fetch {
  return (input, init) => {
    const headers = new Headers(
      typeof Request !== 'undefined' && input instanceof Request ? input.headers : undefined,
    );

    if (init?.headers) {
      new Headers(init.headers).forEach((value, key) => headers.set(key, value));
    }

    // New Supabase API keys are opaque strings, not bearer JWTs.
    if (isNewSupabaseApiKey(supabaseKey) && headers.get('Authorization') === `Bearer ${supabaseKey}`) {
      headers.delete('Authorization');
    }

    headers.set('apikey', supabaseKey);
    return fetch(input, { ...init, headers });
  };
}

async function createSupabaseClient() {
  // Lazy import to avoid loading tslib at SSR module-init time (causes Vercel crash)
  const { createClient } = await import('@supabase/supabase-js');
  const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || process.env.SUPABASE_URL;
  const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || process.env.SUPABASE_PUBLISHABLE_KEY;

  if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
    const missing = [
      ...(!SUPABASE_URL ? ['SUPABASE_URL'] : []),
      ...(!SUPABASE_PUBLISHABLE_KEY ? ['SUPABASE_PUBLISHABLE_KEY'] : []),
    ];
    console.error(`[Supabase] Missing: ${missing.join(', ')}`);
  }

  return createClient<Database>(SUPABASE_URL || 'https://placeholder.supabase.co', SUPABASE_PUBLISHABLE_KEY || 'placeholder-key', {
    global: {
      fetch: createSupabaseFetch(SUPABASE_PUBLISHABLE_KEY || ''),
    },
    auth: {
      storage: typeof window !== 'undefined' ? localStorage : undefined,
      persistSession: true,
      autoRefreshToken: true,
    }
  });
}

let _supabasePromise: Promise<Awaited<ReturnType<typeof createSupabaseClient>>> | undefined;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
export const supabase = new Proxy({} as Awaited<ReturnType<typeof createSupabaseClient>>, {
  get(_, prop, receiver) {
    if (!_supabasePromise) _supabasePromise = createSupabaseClient();
    // Return a thenable proxy for async access
    return new Proxy(() => {}, {
      apply(_t, _this, args) {
        return _supabasePromise!.then((client) => {
          const fn = Reflect.get(client, prop, receiver);
          if (typeof fn === 'function') return fn.apply(client, args);
          return fn;
        });
      },
      get(_t, innerProp, innerReceiver) {
        return _supabasePromise!.then((client) => {
          const val = Reflect.get(client, prop, receiver);
          if (val && typeof val === 'object') return Reflect.get(val, innerProp, innerReceiver);
          return undefined;
        });
      }
    });
  },
});
